# Generated by Django 3.1 on 2020-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('DEVELOPER', 'Developer'), ('TEAMLEAD', 'Team Leader'), ('PROJECTMANAGER', 'Project Manager')], default='DEVELOPER', max_length=255, null=True),
        ),
    ]
